// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Box.proto

package com.bestarmedia.proto.vod;

/**
 * <pre>
 * 机顶盒认证请求
 * </pre>
 *
 * Protobuf type {@code BoxAuthRequest}
 */
public  final class BoxAuthRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BoxAuthRequest)
    BoxAuthRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoxAuthRequest.newBuilder() to construct.
  private BoxAuthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoxAuthRequest() {
    ktvNetCode_ = "";
    roomCode_ = "";
    serialNo_ = "";
    anufacturer_ = "";
    apkVersionName_ = "";
    ip_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoxAuthRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            ktvNetCode_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            roomCode_ = s;
            break;
          }
          case 24: {

            hdmiEnable_ = input.readInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            serialNo_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            anufacturer_ = s;
            break;
          }
          case 48: {

            osVersion_ = input.readInt32();
            break;
          }
          case 56: {

            apkVersionCode_ = input.readInt32();
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            apkVersionName_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BoxProto.internal_static_BoxAuthRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BoxProto.internal_static_BoxAuthRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BoxAuthRequest.class, Builder.class);
  }

  public static final int KTV_NET_CODE_FIELD_NUMBER = 1;
  private volatile Object ktvNetCode_;
  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 1;</code>
   */
  public String getKtvNetCode() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvNetCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNetCodeBytes() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 2;
  private volatile Object roomCode_;
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 2;</code>
   */
  public String getRoomCode() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HDMI_ENABLE_FIELD_NUMBER = 3;
  private int hdmiEnable_;
  /**
   * <pre>
   * HDMI状态 0未开启 1已开启
   * </pre>
   *
   * <code>int32 hdmi_enable = 3;</code>
   */
  public int getHdmiEnable() {
    return hdmiEnable_;
  }

  public static final int SERIAL_NO_FIELD_NUMBER = 4;
  private volatile Object serialNo_;
  /**
   * <pre>
   * 机顶盒序列号
   * </pre>
   *
   * <code>string serial_no = 4;</code>
   */
  public String getSerialNo() {
    Object ref = serialNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serialNo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 机顶盒序列号
   * </pre>
   *
   * <code>string serial_no = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSerialNoBytes() {
    Object ref = serialNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serialNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANUFACTURER_FIELD_NUMBER = 5;
  private volatile Object anufacturer_;
  /**
   * <pre>
   *厂商
   * </pre>
   *
   * <code>string anufacturer = 5;</code>
   */
  public String getAnufacturer() {
    Object ref = anufacturer_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      anufacturer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *厂商
   * </pre>
   *
   * <code>string anufacturer = 5;</code>
   */
  public com.google.protobuf.ByteString
      getAnufacturerBytes() {
    Object ref = anufacturer_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      anufacturer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OS_VERSION_FIELD_NUMBER = 6;
  private int osVersion_;
  /**
   * <pre>
   *系统版本号
   * </pre>
   *
   * <code>int32 os_version = 6;</code>
   */
  public int getOsVersion() {
    return osVersion_;
  }

  public static final int APK_VERSION_CODE_FIELD_NUMBER = 7;
  private int apkVersionCode_;
  /**
   * <pre>
   *APP版本号
   * </pre>
   *
   * <code>int32 apk_version_code = 7;</code>
   */
  public int getApkVersionCode() {
    return apkVersionCode_;
  }

  public static final int APK_VERSION_NAME_FIELD_NUMBER = 8;
  private volatile Object apkVersionName_;
  /**
   * <pre>
   *APP版本名称
   * </pre>
   *
   * <code>string apk_version_name = 8;</code>
   */
  public String getApkVersionName() {
    Object ref = apkVersionName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      apkVersionName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *APP版本名称
   * </pre>
   *
   * <code>string apk_version_name = 8;</code>
   */
  public com.google.protobuf.ByteString
      getApkVersionNameBytes() {
    Object ref = apkVersionName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      apkVersionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 9;
  private volatile Object ip_;
  /**
   * <pre>
   *设备IP
   * </pre>
   *
   * <code>string ip = 9;</code>
   */
  public String getIp() {
    Object ref = ip_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备IP
   * </pre>
   *
   * <code>string ip = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    Object ref = ip_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomCode_);
    }
    if (hdmiEnable_ != 0) {
      output.writeInt32(3, hdmiEnable_);
    }
    if (!getSerialNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serialNo_);
    }
    if (!getAnufacturerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, anufacturer_);
    }
    if (osVersion_ != 0) {
      output.writeInt32(6, osVersion_);
    }
    if (apkVersionCode_ != 0) {
      output.writeInt32(7, apkVersionCode_);
    }
    if (!getApkVersionNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, apkVersionName_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ip_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomCode_);
    }
    if (hdmiEnable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, hdmiEnable_);
    }
    if (!getSerialNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serialNo_);
    }
    if (!getAnufacturerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, anufacturer_);
    }
    if (osVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, osVersion_);
    }
    if (apkVersionCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, apkVersionCode_);
    }
    if (!getApkVersionNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, apkVersionName_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ip_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BoxAuthRequest)) {
      return super.equals(obj);
    }
    BoxAuthRequest other = (BoxAuthRequest) obj;

    if (!getKtvNetCode()
        .equals(other.getKtvNetCode())) return false;
    if (!getRoomCode()
        .equals(other.getRoomCode())) return false;
    if (getHdmiEnable()
        != other.getHdmiEnable()) return false;
    if (!getSerialNo()
        .equals(other.getSerialNo())) return false;
    if (!getAnufacturer()
        .equals(other.getAnufacturer())) return false;
    if (getOsVersion()
        != other.getOsVersion()) return false;
    if (getApkVersionCode()
        != other.getApkVersionCode()) return false;
    if (!getApkVersionName()
        .equals(other.getApkVersionName())) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvNetCode().hashCode();
    hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoomCode().hashCode();
    hash = (37 * hash) + HDMI_ENABLE_FIELD_NUMBER;
    hash = (53 * hash) + getHdmiEnable();
    hash = (37 * hash) + SERIAL_NO_FIELD_NUMBER;
    hash = (53 * hash) + getSerialNo().hashCode();
    hash = (37 * hash) + ANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + getAnufacturer().hashCode();
    hash = (37 * hash) + OS_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getOsVersion();
    hash = (37 * hash) + APK_VERSION_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getApkVersionCode();
    hash = (37 * hash) + APK_VERSION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getApkVersionName().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BoxAuthRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoxAuthRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoxAuthRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoxAuthRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoxAuthRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BoxAuthRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BoxAuthRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BoxAuthRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BoxAuthRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BoxAuthRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BoxAuthRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BoxAuthRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BoxAuthRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 机顶盒认证请求
   * </pre>
   *
   * Protobuf type {@code BoxAuthRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BoxAuthRequest)
      BoxAuthRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoxProto.internal_static_BoxAuthRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoxProto.internal_static_BoxAuthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BoxAuthRequest.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.vod.BoxAuthRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      ktvNetCode_ = "";

      roomCode_ = "";

      hdmiEnable_ = 0;

      serialNo_ = "";

      anufacturer_ = "";

      osVersion_ = 0;

      apkVersionCode_ = 0;

      apkVersionName_ = "";

      ip_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BoxProto.internal_static_BoxAuthRequest_descriptor;
    }

    @Override
    public BoxAuthRequest getDefaultInstanceForType() {
      return BoxAuthRequest.getDefaultInstance();
    }

    @Override
    public BoxAuthRequest build() {
      BoxAuthRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BoxAuthRequest buildPartial() {
      BoxAuthRequest result = new BoxAuthRequest(this);
      result.ktvNetCode_ = ktvNetCode_;
      result.roomCode_ = roomCode_;
      result.hdmiEnable_ = hdmiEnable_;
      result.serialNo_ = serialNo_;
      result.anufacturer_ = anufacturer_;
      result.osVersion_ = osVersion_;
      result.apkVersionCode_ = apkVersionCode_;
      result.apkVersionName_ = apkVersionName_;
      result.ip_ = ip_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BoxAuthRequest) {
        return mergeFrom((BoxAuthRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BoxAuthRequest other) {
      if (other == BoxAuthRequest.getDefaultInstance()) return this;
      if (!other.getKtvNetCode().isEmpty()) {
        ktvNetCode_ = other.ktvNetCode_;
        onChanged();
      }
      if (!other.getRoomCode().isEmpty()) {
        roomCode_ = other.roomCode_;
        onChanged();
      }
      if (other.getHdmiEnable() != 0) {
        setHdmiEnable(other.getHdmiEnable());
      }
      if (!other.getSerialNo().isEmpty()) {
        serialNo_ = other.serialNo_;
        onChanged();
      }
      if (!other.getAnufacturer().isEmpty()) {
        anufacturer_ = other.anufacturer_;
        onChanged();
      }
      if (other.getOsVersion() != 0) {
        setOsVersion(other.getOsVersion());
      }
      if (other.getApkVersionCode() != 0) {
        setApkVersionCode(other.getApkVersionCode());
      }
      if (!other.getApkVersionName().isEmpty()) {
        apkVersionName_ = other.apkVersionName_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BoxAuthRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BoxAuthRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object ktvNetCode_ = "";
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 1;</code>
     */
    public String getKtvNetCode() {
      Object ref = ktvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNetCodeBytes() {
      Object ref = ktvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder setKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder clearKtvNetCode() {
      
      ktvNetCode_ = getDefaultInstance().getKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder setKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvNetCode_ = value;
      onChanged();
      return this;
    }

    private Object roomCode_ = "";
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 2;</code>
     */
    public String getRoomCode() {
      Object ref = roomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 2;</code>
     */
    public Builder setRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 2;</code>
     */
    public Builder clearRoomCode() {
      
      roomCode_ = getDefaultInstance().getRoomCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 2;</code>
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomCode_ = value;
      onChanged();
      return this;
    }

    private int hdmiEnable_ ;
    /**
     * <pre>
     * HDMI状态 0未开启 1已开启
     * </pre>
     *
     * <code>int32 hdmi_enable = 3;</code>
     */
    public int getHdmiEnable() {
      return hdmiEnable_;
    }
    /**
     * <pre>
     * HDMI状态 0未开启 1已开启
     * </pre>
     *
     * <code>int32 hdmi_enable = 3;</code>
     */
    public Builder setHdmiEnable(int value) {
      
      hdmiEnable_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HDMI状态 0未开启 1已开启
     * </pre>
     *
     * <code>int32 hdmi_enable = 3;</code>
     */
    public Builder clearHdmiEnable() {
      
      hdmiEnable_ = 0;
      onChanged();
      return this;
    }

    private Object serialNo_ = "";
    /**
     * <pre>
     * 机顶盒序列号
     * </pre>
     *
     * <code>string serial_no = 4;</code>
     */
    public String getSerialNo() {
      Object ref = serialNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serialNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 机顶盒序列号
     * </pre>
     *
     * <code>string serial_no = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSerialNoBytes() {
      Object ref = serialNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serialNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 机顶盒序列号
     * </pre>
     *
     * <code>string serial_no = 4;</code>
     */
    public Builder setSerialNo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serialNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 机顶盒序列号
     * </pre>
     *
     * <code>string serial_no = 4;</code>
     */
    public Builder clearSerialNo() {
      
      serialNo_ = getDefaultInstance().getSerialNo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 机顶盒序列号
     * </pre>
     *
     * <code>string serial_no = 4;</code>
     */
    public Builder setSerialNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serialNo_ = value;
      onChanged();
      return this;
    }

    private Object anufacturer_ = "";
    /**
     * <pre>
     *厂商
     * </pre>
     *
     * <code>string anufacturer = 5;</code>
     */
    public String getAnufacturer() {
      Object ref = anufacturer_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        anufacturer_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *厂商
     * </pre>
     *
     * <code>string anufacturer = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAnufacturerBytes() {
      Object ref = anufacturer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        anufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *厂商
     * </pre>
     *
     * <code>string anufacturer = 5;</code>
     */
    public Builder setAnufacturer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      anufacturer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商
     * </pre>
     *
     * <code>string anufacturer = 5;</code>
     */
    public Builder clearAnufacturer() {
      
      anufacturer_ = getDefaultInstance().getAnufacturer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商
     * </pre>
     *
     * <code>string anufacturer = 5;</code>
     */
    public Builder setAnufacturerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      anufacturer_ = value;
      onChanged();
      return this;
    }

    private int osVersion_ ;
    /**
     * <pre>
     *系统版本号
     * </pre>
     *
     * <code>int32 os_version = 6;</code>
     */
    public int getOsVersion() {
      return osVersion_;
    }
    /**
     * <pre>
     *系统版本号
     * </pre>
     *
     * <code>int32 os_version = 6;</code>
     */
    public Builder setOsVersion(int value) {
      
      osVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统版本号
     * </pre>
     *
     * <code>int32 os_version = 6;</code>
     */
    public Builder clearOsVersion() {
      
      osVersion_ = 0;
      onChanged();
      return this;
    }

    private int apkVersionCode_ ;
    /**
     * <pre>
     *APP版本号
     * </pre>
     *
     * <code>int32 apk_version_code = 7;</code>
     */
    public int getApkVersionCode() {
      return apkVersionCode_;
    }
    /**
     * <pre>
     *APP版本号
     * </pre>
     *
     * <code>int32 apk_version_code = 7;</code>
     */
    public Builder setApkVersionCode(int value) {
      
      apkVersionCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *APP版本号
     * </pre>
     *
     * <code>int32 apk_version_code = 7;</code>
     */
    public Builder clearApkVersionCode() {
      
      apkVersionCode_ = 0;
      onChanged();
      return this;
    }

    private Object apkVersionName_ = "";
    /**
     * <pre>
     *APP版本名称
     * </pre>
     *
     * <code>string apk_version_name = 8;</code>
     */
    public String getApkVersionName() {
      Object ref = apkVersionName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        apkVersionName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *APP版本名称
     * </pre>
     *
     * <code>string apk_version_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getApkVersionNameBytes() {
      Object ref = apkVersionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        apkVersionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *APP版本名称
     * </pre>
     *
     * <code>string apk_version_name = 8;</code>
     */
    public Builder setApkVersionName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      apkVersionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *APP版本名称
     * </pre>
     *
     * <code>string apk_version_name = 8;</code>
     */
    public Builder clearApkVersionName() {
      
      apkVersionName_ = getDefaultInstance().getApkVersionName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *APP版本名称
     * </pre>
     *
     * <code>string apk_version_name = 8;</code>
     */
    public Builder setApkVersionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      apkVersionName_ = value;
      onChanged();
      return this;
    }

    private Object ip_ = "";
    /**
     * <pre>
     *设备IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *设备IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public Builder setIp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BoxAuthRequest)
  }

  // @@protoc_insertion_point(class_scope:BoxAuthRequest)
  private static final BoxAuthRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BoxAuthRequest();
  }

  public static BoxAuthRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoxAuthRequest>
      PARSER = new com.google.protobuf.AbstractParser<BoxAuthRequest>() {
    @Override
    public BoxAuthRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoxAuthRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoxAuthRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BoxAuthRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public BoxAuthRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

