// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Box.proto

package com.bestarmedia.proto.vod;

public interface ButtonStatusBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ButtonStatusBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  boolean hasButton();
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  Button getButton();
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  ButtonOrBuilder getButtonOrBuilder();

  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  boolean hasUser();
  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  com.bestarmedia.proto.vod.MobileUser getUser();
  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  com.bestarmedia.proto.vod.MobileUserOrBuilder getUserOrBuilder();
}
