// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Box.proto

package com.bestarmedia.proto.vod;

/**
 * <pre>
 * 按钮状态
 * </pre>
 *
 * Protobuf type {@code ButtonStatusBroadcast}
 */
public  final class ButtonStatusBroadcast extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ButtonStatusBroadcast)
    ButtonStatusBroadcastOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ButtonStatusBroadcast.newBuilder() to construct.
  private ButtonStatusBroadcast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ButtonStatusBroadcast() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ButtonStatusBroadcast(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Button.Builder subBuilder = null;
            if (button_ != null) {
              subBuilder = button_.toBuilder();
            }
            button_ = input.readMessage(Button.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(button_);
              button_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.bestarmedia.proto.vod.MobileUser.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(com.bestarmedia.proto.vod.MobileUser.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BoxProto.internal_static_ButtonStatusBroadcast_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BoxProto.internal_static_ButtonStatusBroadcast_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ButtonStatusBroadcast.class, Builder.class);
  }

  public static final int BUTTON_FIELD_NUMBER = 1;
  private Button button_;
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  public boolean hasButton() {
    return button_ != null;
  }
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  public Button getButton() {
    return button_ == null ? Button.getDefaultInstance() : button_;
  }
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * <code>.Button button = 1;</code>
   */
  public ButtonOrBuilder getButtonOrBuilder() {
    return getButton();
  }

  public static final int USER_FIELD_NUMBER = 2;
  private com.bestarmedia.proto.vod.MobileUser user_;
  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  public com.bestarmedia.proto.vod.MobileUser getUser() {
    return user_ == null ? com.bestarmedia.proto.vod.MobileUser.getDefaultInstance() : user_;
  }
  /**
   * <pre>
   * 用户消息
   * </pre>
   *
   * <code>.MobileUser user = 2;</code>
   */
  public com.bestarmedia.proto.vod.MobileUserOrBuilder getUserOrBuilder() {
    return getUser();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (button_ != null) {
      output.writeMessage(1, getButton());
    }
    if (user_ != null) {
      output.writeMessage(2, getUser());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (button_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getButton());
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUser());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ButtonStatusBroadcast)) {
      return super.equals(obj);
    }
    ButtonStatusBroadcast other = (ButtonStatusBroadcast) obj;

    if (hasButton() != other.hasButton()) return false;
    if (hasButton()) {
      if (!getButton()
          .equals(other.getButton())) return false;
    }
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasButton()) {
      hash = (37 * hash) + BUTTON_FIELD_NUMBER;
      hash = (53 * hash) + getButton().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ButtonStatusBroadcast parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ButtonStatusBroadcast parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ButtonStatusBroadcast parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ButtonStatusBroadcast parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ButtonStatusBroadcast parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ButtonStatusBroadcast parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ButtonStatusBroadcast parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ButtonStatusBroadcast parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ButtonStatusBroadcast parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ButtonStatusBroadcast parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ButtonStatusBroadcast parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ButtonStatusBroadcast parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ButtonStatusBroadcast prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 按钮状态
   * </pre>
   *
   * Protobuf type {@code ButtonStatusBroadcast}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ButtonStatusBroadcast)
      com.bestarmedia.proto.vod.ButtonStatusBroadcastOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoxProto.internal_static_ButtonStatusBroadcast_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoxProto.internal_static_ButtonStatusBroadcast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ButtonStatusBroadcast.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.vod.ButtonStatusBroadcast.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (buttonBuilder_ == null) {
        button_ = null;
      } else {
        button_ = null;
        buttonBuilder_ = null;
      }
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BoxProto.internal_static_ButtonStatusBroadcast_descriptor;
    }

    @Override
    public ButtonStatusBroadcast getDefaultInstanceForType() {
      return ButtonStatusBroadcast.getDefaultInstance();
    }

    @Override
    public ButtonStatusBroadcast build() {
      ButtonStatusBroadcast result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ButtonStatusBroadcast buildPartial() {
      ButtonStatusBroadcast result = new ButtonStatusBroadcast(this);
      if (buttonBuilder_ == null) {
        result.button_ = button_;
      } else {
        result.button_ = buttonBuilder_.build();
      }
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ButtonStatusBroadcast) {
        return mergeFrom((ButtonStatusBroadcast)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ButtonStatusBroadcast other) {
      if (other == ButtonStatusBroadcast.getDefaultInstance()) return this;
      if (other.hasButton()) {
        mergeButton(other.getButton());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ButtonStatusBroadcast parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ButtonStatusBroadcast) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Button button_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Button, Button.Builder, ButtonOrBuilder> buttonBuilder_;
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public boolean hasButton() {
      return buttonBuilder_ != null || button_ != null;
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Button getButton() {
      if (buttonBuilder_ == null) {
        return button_ == null ? Button.getDefaultInstance() : button_;
      } else {
        return buttonBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Builder setButton(Button value) {
      if (buttonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        button_ = value;
        onChanged();
      } else {
        buttonBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Builder setButton(
        Button.Builder builderForValue) {
      if (buttonBuilder_ == null) {
        button_ = builderForValue.build();
        onChanged();
      } else {
        buttonBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Builder mergeButton(Button value) {
      if (buttonBuilder_ == null) {
        if (button_ != null) {
          button_ =
            Button.newBuilder(button_).mergeFrom(value).buildPartial();
        } else {
          button_ = value;
        }
        onChanged();
      } else {
        buttonBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Builder clearButton() {
      if (buttonBuilder_ == null) {
        button_ = null;
        onChanged();
      } else {
        button_ = null;
        buttonBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public Button.Builder getButtonBuilder() {
      
      onChanged();
      return getButtonFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    public ButtonOrBuilder getButtonOrBuilder() {
      if (buttonBuilder_ != null) {
        return buttonBuilder_.getMessageOrBuilder();
      } else {
        return button_ == null ?
            Button.getDefaultInstance() : button_;
      }
    }
    /**
     * <pre>
     * 按钮状态
     * </pre>
     *
     * <code>.Button button = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Button, Button.Builder, ButtonOrBuilder>
        getButtonFieldBuilder() {
      if (buttonBuilder_ == null) {
        buttonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Button, Button.Builder, ButtonOrBuilder>(
                getButton(),
                getParentForChildren(),
                isClean());
        button_ = null;
      }
      return buttonBuilder_;
    }

    private com.bestarmedia.proto.vod.MobileUser user_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bestarmedia.proto.vod.MobileUser, com.bestarmedia.proto.vod.MobileUser.Builder, com.bestarmedia.proto.vod.MobileUserOrBuilder> userBuilder_;
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public com.bestarmedia.proto.vod.MobileUser getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.bestarmedia.proto.vod.MobileUser.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public Builder setUser(com.bestarmedia.proto.vod.MobileUser value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public Builder setUser(
        com.bestarmedia.proto.vod.MobileUser.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public Builder mergeUser(com.bestarmedia.proto.vod.MobileUser value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            com.bestarmedia.proto.vod.MobileUser.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public com.bestarmedia.proto.vod.MobileUser.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    public com.bestarmedia.proto.vod.MobileUserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.bestarmedia.proto.vod.MobileUser.getDefaultInstance() : user_;
      }
    }
    /**
     * <pre>
     * 用户消息
     * </pre>
     *
     * <code>.MobileUser user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bestarmedia.proto.vod.MobileUser, com.bestarmedia.proto.vod.MobileUser.Builder, com.bestarmedia.proto.vod.MobileUserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bestarmedia.proto.vod.MobileUser, com.bestarmedia.proto.vod.MobileUser.Builder, com.bestarmedia.proto.vod.MobileUserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ButtonStatusBroadcast)
  }

  // @@protoc_insertion_point(class_scope:ButtonStatusBroadcast)
  private static final ButtonStatusBroadcast DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ButtonStatusBroadcast();
  }

  public static ButtonStatusBroadcast getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ButtonStatusBroadcast>
      PARSER = new com.google.protobuf.AbstractParser<ButtonStatusBroadcast>() {
    @Override
    public ButtonStatusBroadcast parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ButtonStatusBroadcast(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ButtonStatusBroadcast> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ButtonStatusBroadcast> getParserForType() {
    return PARSER;
  }

  @Override
  public ButtonStatusBroadcast getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

