// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Box.proto

package com.bestarmedia.proto.vod;

public interface MobileMessageBroadcastOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MobileMessageBroadcast)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MobileUser user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.MobileUser user = 1;</code>
   */
  com.bestarmedia.proto.vod.MobileUser getUser();
  /**
   * <code>.MobileUser user = 1;</code>
   */
  com.bestarmedia.proto.vod.MobileUserOrBuilder getUserOrBuilder();

  /**
   * <pre>
   * 消息指令（原消息号，根据此消息号来判断是什么指令动作）
   * </pre>
   *
   * <code>int32 directive = 2;</code>
   */
  int getDirective();

  /**
   * <pre>
   * 文本 (弹幕) 可以为空
   * </pre>
   *
   * <code>.Text text = 3;</code>
   */
  boolean hasText();
  /**
   * <pre>
   * 文本 (弹幕) 可以为空
   * </pre>
   *
   * <code>.Text text = 3;</code>
   */
  com.bestarmedia.proto.node.Text getText();
  /**
   * <pre>
   * 文本 (弹幕) 可以为空
   * </pre>
   *
   * <code>.Text text = 3;</code>
   */
  com.bestarmedia.proto.node.TextOrBuilder getTextOrBuilder();

  /**
   * <pre>
   * 图片 可以为空
   * </pre>
   *
   * <code>.Image image = 4;</code>
   */
  boolean hasImage();
  /**
   * <pre>
   * 图片 可以为空
   * </pre>
   *
   * <code>.Image image = 4;</code>
   */
  com.bestarmedia.proto.node.Image getImage();
  /**
   * <pre>
   * 图片 可以为空
   * </pre>
   *
   * <code>.Image image = 4;</code>
   */
  com.bestarmedia.proto.node.ImageOrBuilder getImageOrBuilder();

  /**
   * <pre>
   * ID类值（歌曲ID，气氛表情ID）
   * </pre>
   *
   * <code>string id = 5;</code>
   */
  String getId();
  /**
   * <pre>
   * ID类值（歌曲ID，气氛表情ID）
   * </pre>
   *
   * <code>string id = 5;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 斗歌得分
   * </pre>
   *
   * <code>string score = 6;</code>
   */
  String getScore();
  /**
   * <pre>
   * 斗歌得分
   * </pre>
   *
   * <code>string score = 6;</code>
   */
  com.google.protobuf.ByteString
      getScoreBytes();
}
