// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Battle.proto

package com.bestarmedia.proto.vod;

/**
 * <pre>
 * 发送给对方的得分
 * </pre>
 *
 * Protobuf type {@code ScoreToOpponent}
 */
public  final class ScoreToOpponent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ScoreToOpponent)
    ScoreToOpponentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScoreToOpponent.newBuilder() to construct.
  private ScoreToOpponent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScoreToOpponent() {
    opponentKtvNetCode_ = "";
    opponentRoomCode_ = "";
    text_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScoreToOpponent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            BattleUser.Builder subBuilder = null;
            if (currentUser_ != null) {
              subBuilder = currentUser_.toBuilder();
            }
            currentUser_ = input.readMessage(BattleUser.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentUser_);
              currentUser_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            opponentKtvNetCode_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            opponentRoomCode_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 40: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BattleProto.internal_static_ScoreToOpponent_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BattleProto.internal_static_ScoreToOpponent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ScoreToOpponent.class, Builder.class);
  }

  public static final int CURRENT_USER_FIELD_NUMBER = 1;
  private BattleUser currentUser_;
  /**
   * <pre>
   * 我的得分
   * </pre>
   *
   * <code>.BattleUser current_user = 1;</code>
   */
  public boolean hasCurrentUser() {
    return currentUser_ != null;
  }
  /**
   * <pre>
   * 我的得分
   * </pre>
   *
   * <code>.BattleUser current_user = 1;</code>
   */
  public BattleUser getCurrentUser() {
    return currentUser_ == null ? BattleUser.getDefaultInstance() : currentUser_;
  }
  /**
   * <pre>
   * 我的得分
   * </pre>
   *
   * <code>.BattleUser current_user = 1;</code>
   */
  public BattleUserOrBuilder getCurrentUserOrBuilder() {
    return getCurrentUser();
  }

  public static final int OPPONENT_KTV_NET_CODE_FIELD_NUMBER = 2;
  private volatile Object opponentKtvNetCode_;
  /**
   * <pre>
   * 对方KTV编号
   * </pre>
   *
   * <code>string opponent_ktv_net_code = 2;</code>
   */
  public String getOpponentKtvNetCode() {
    Object ref = opponentKtvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      opponentKtvNetCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 对方KTV编号
   * </pre>
   *
   * <code>string opponent_ktv_net_code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOpponentKtvNetCodeBytes() {
    Object ref = opponentKtvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      opponentKtvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPPONENT_ROOM_CODE_FIELD_NUMBER = 3;
  private volatile Object opponentRoomCode_;
  /**
   * <pre>
   * 对方房间号
   * </pre>
   *
   * <code>string opponent_room_code = 3;</code>
   */
  public String getOpponentRoomCode() {
    Object ref = opponentRoomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      opponentRoomCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 对方房间号
   * </pre>
   *
   * <code>string opponent_room_code = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOpponentRoomCodeBytes() {
    Object ref = opponentRoomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      opponentRoomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_FIELD_NUMBER = 4;
  private volatile Object text_;
  /**
   * <pre>
   * 弹幕文本
   * </pre>
   *
   * <code>string text = 4;</code>
   */
  public String getText() {
    Object ref = text_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 弹幕文本
   * </pre>
   *
   * <code>string text = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    Object ref = text_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 5;
  private int id_;
  /**
   * <pre>
   * 斗歌记录ID
   * </pre>
   *
   * <code>int32 id = 5;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentUser_ != null) {
      output.writeMessage(1, getCurrentUser());
    }
    if (!getOpponentKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, opponentKtvNetCode_);
    }
    if (!getOpponentRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, opponentRoomCode_);
    }
    if (!getTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_);
    }
    if (id_ != 0) {
      output.writeInt32(5, id_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCurrentUser());
    }
    if (!getOpponentKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, opponentKtvNetCode_);
    }
    if (!getOpponentRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, opponentRoomCode_);
    }
    if (!getTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ScoreToOpponent)) {
      return super.equals(obj);
    }
    ScoreToOpponent other = (ScoreToOpponent) obj;

    if (hasCurrentUser() != other.hasCurrentUser()) return false;
    if (hasCurrentUser()) {
      if (!getCurrentUser()
          .equals(other.getCurrentUser())) return false;
    }
    if (!getOpponentKtvNetCode()
        .equals(other.getOpponentKtvNetCode())) return false;
    if (!getOpponentRoomCode()
        .equals(other.getOpponentRoomCode())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCurrentUser()) {
      hash = (37 * hash) + CURRENT_USER_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentUser().hashCode();
    }
    hash = (37 * hash) + OPPONENT_KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getOpponentKtvNetCode().hashCode();
    hash = (37 * hash) + OPPONENT_ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getOpponentRoomCode().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ScoreToOpponent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScoreToOpponent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScoreToOpponent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScoreToOpponent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScoreToOpponent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScoreToOpponent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScoreToOpponent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScoreToOpponent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScoreToOpponent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ScoreToOpponent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScoreToOpponent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScoreToOpponent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ScoreToOpponent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 发送给对方的得分
   * </pre>
   *
   * Protobuf type {@code ScoreToOpponent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ScoreToOpponent)
      com.bestarmedia.proto.vod.ScoreToOpponentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BattleProto.internal_static_ScoreToOpponent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BattleProto.internal_static_ScoreToOpponent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScoreToOpponent.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.vod.ScoreToOpponent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (currentUserBuilder_ == null) {
        currentUser_ = null;
      } else {
        currentUser_ = null;
        currentUserBuilder_ = null;
      }
      opponentKtvNetCode_ = "";

      opponentRoomCode_ = "";

      text_ = "";

      id_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BattleProto.internal_static_ScoreToOpponent_descriptor;
    }

    @Override
    public ScoreToOpponent getDefaultInstanceForType() {
      return ScoreToOpponent.getDefaultInstance();
    }

    @Override
    public ScoreToOpponent build() {
      ScoreToOpponent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ScoreToOpponent buildPartial() {
      ScoreToOpponent result = new ScoreToOpponent(this);
      if (currentUserBuilder_ == null) {
        result.currentUser_ = currentUser_;
      } else {
        result.currentUser_ = currentUserBuilder_.build();
      }
      result.opponentKtvNetCode_ = opponentKtvNetCode_;
      result.opponentRoomCode_ = opponentRoomCode_;
      result.text_ = text_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ScoreToOpponent) {
        return mergeFrom((ScoreToOpponent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ScoreToOpponent other) {
      if (other == ScoreToOpponent.getDefaultInstance()) return this;
      if (other.hasCurrentUser()) {
        mergeCurrentUser(other.getCurrentUser());
      }
      if (!other.getOpponentKtvNetCode().isEmpty()) {
        opponentKtvNetCode_ = other.opponentKtvNetCode_;
        onChanged();
      }
      if (!other.getOpponentRoomCode().isEmpty()) {
        opponentRoomCode_ = other.opponentRoomCode_;
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ScoreToOpponent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ScoreToOpponent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private BattleUser currentUser_;
    private com.google.protobuf.SingleFieldBuilderV3<
        BattleUser, BattleUser.Builder, BattleUserOrBuilder> currentUserBuilder_;
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public boolean hasCurrentUser() {
      return currentUserBuilder_ != null || currentUser_ != null;
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public BattleUser getCurrentUser() {
      if (currentUserBuilder_ == null) {
        return currentUser_ == null ? BattleUser.getDefaultInstance() : currentUser_;
      } else {
        return currentUserBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public Builder setCurrentUser(BattleUser value) {
      if (currentUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentUser_ = value;
        onChanged();
      } else {
        currentUserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public Builder setCurrentUser(
        BattleUser.Builder builderForValue) {
      if (currentUserBuilder_ == null) {
        currentUser_ = builderForValue.build();
        onChanged();
      } else {
        currentUserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public Builder mergeCurrentUser(BattleUser value) {
      if (currentUserBuilder_ == null) {
        if (currentUser_ != null) {
          currentUser_ =
            BattleUser.newBuilder(currentUser_).mergeFrom(value).buildPartial();
        } else {
          currentUser_ = value;
        }
        onChanged();
      } else {
        currentUserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public Builder clearCurrentUser() {
      if (currentUserBuilder_ == null) {
        currentUser_ = null;
        onChanged();
      } else {
        currentUser_ = null;
        currentUserBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public BattleUser.Builder getCurrentUserBuilder() {
      
      onChanged();
      return getCurrentUserFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    public BattleUserOrBuilder getCurrentUserOrBuilder() {
      if (currentUserBuilder_ != null) {
        return currentUserBuilder_.getMessageOrBuilder();
      } else {
        return currentUser_ == null ?
            BattleUser.getDefaultInstance() : currentUser_;
      }
    }
    /**
     * <pre>
     * 我的得分
     * </pre>
     *
     * <code>.BattleUser current_user = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        BattleUser, BattleUser.Builder, BattleUserOrBuilder>
        getCurrentUserFieldBuilder() {
      if (currentUserBuilder_ == null) {
        currentUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            BattleUser, BattleUser.Builder, BattleUserOrBuilder>(
                getCurrentUser(),
                getParentForChildren(),
                isClean());
        currentUser_ = null;
      }
      return currentUserBuilder_;
    }

    private Object opponentKtvNetCode_ = "";
    /**
     * <pre>
     * 对方KTV编号
     * </pre>
     *
     * <code>string opponent_ktv_net_code = 2;</code>
     */
    public String getOpponentKtvNetCode() {
      Object ref = opponentKtvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        opponentKtvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 对方KTV编号
     * </pre>
     *
     * <code>string opponent_ktv_net_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOpponentKtvNetCodeBytes() {
      Object ref = opponentKtvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        opponentKtvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 对方KTV编号
     * </pre>
     *
     * <code>string opponent_ktv_net_code = 2;</code>
     */
    public Builder setOpponentKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      opponentKtvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对方KTV编号
     * </pre>
     *
     * <code>string opponent_ktv_net_code = 2;</code>
     */
    public Builder clearOpponentKtvNetCode() {
      
      opponentKtvNetCode_ = getDefaultInstance().getOpponentKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对方KTV编号
     * </pre>
     *
     * <code>string opponent_ktv_net_code = 2;</code>
     */
    public Builder setOpponentKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      opponentKtvNetCode_ = value;
      onChanged();
      return this;
    }

    private Object opponentRoomCode_ = "";
    /**
     * <pre>
     * 对方房间号
     * </pre>
     *
     * <code>string opponent_room_code = 3;</code>
     */
    public String getOpponentRoomCode() {
      Object ref = opponentRoomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        opponentRoomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 对方房间号
     * </pre>
     *
     * <code>string opponent_room_code = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOpponentRoomCodeBytes() {
      Object ref = opponentRoomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        opponentRoomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 对方房间号
     * </pre>
     *
     * <code>string opponent_room_code = 3;</code>
     */
    public Builder setOpponentRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      opponentRoomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对方房间号
     * </pre>
     *
     * <code>string opponent_room_code = 3;</code>
     */
    public Builder clearOpponentRoomCode() {
      
      opponentRoomCode_ = getDefaultInstance().getOpponentRoomCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对方房间号
     * </pre>
     *
     * <code>string opponent_room_code = 3;</code>
     */
    public Builder setOpponentRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      opponentRoomCode_ = value;
      onChanged();
      return this;
    }

    private Object text_ = "";
    /**
     * <pre>
     * 弹幕文本
     * </pre>
     *
     * <code>string text = 4;</code>
     */
    public String getText() {
      Object ref = text_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 弹幕文本
     * </pre>
     *
     * <code>string text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 弹幕文本
     * </pre>
     *
     * <code>string text = 4;</code>
     */
    public Builder setText(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕文本
     * </pre>
     *
     * <code>string text = 4;</code>
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕文本
     * </pre>
     *
     * <code>string text = 4;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <pre>
     * 斗歌记录ID
     * </pre>
     *
     * <code>int32 id = 5;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <pre>
     * 斗歌记录ID
     * </pre>
     *
     * <code>int32 id = 5;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 斗歌记录ID
     * </pre>
     *
     * <code>int32 id = 5;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ScoreToOpponent)
  }

  // @@protoc_insertion_point(class_scope:ScoreToOpponent)
  private static final ScoreToOpponent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ScoreToOpponent();
  }

  public static ScoreToOpponent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScoreToOpponent>
      PARSER = new com.google.protobuf.AbstractParser<ScoreToOpponent>() {
    @Override
    public ScoreToOpponent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScoreToOpponent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScoreToOpponent> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ScoreToOpponent> getParserForType() {
    return PARSER;
  }

  @Override
  public ScoreToOpponent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

