// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Node.proto

package com.bestarmedia.proto.node;

public interface BarrageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BarrageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int32 user_id = 1;</code>
   */
  int getUserId();

  /**
   * <pre>
   * 用户地址 没有则为空
   * </pre>
   *
   * <code>string address = 2;</code>
   */
  String getAddress();
  /**
   * <pre>
   * 用户地址 没有则为空
   * </pre>
   *
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * 用户名字
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  String getName();
  /**
   * <pre>
   * 用户名字
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *头像
   * </pre>
   *
   * <code>string avatar = 4;</code>
   */
  String getAvatar();
  /**
   * <pre>
   *头像
   * </pre>
   *
   * <code>string avatar = 4;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   * 房间SESSION
   * </pre>
   *
   * <code>string room_session = 5;</code>
   */
  String getRoomSession();
  /**
   * <pre>
   * 房间SESSION
   * </pre>
   *
   * <code>string room_session = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoomSessionBytes();

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 6;</code>
   */
  String getRoomCode();
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 6;</code>
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <pre>
   * KTV ID
   * </pre>
   *
   * <code>string ktv_net_code = 7;</code>
   */
  String getKtvNetCode();
  /**
   * <pre>
   * KTV ID
   * </pre>
   *
   * <code>string ktv_net_code = 7;</code>
   */
  com.google.protobuf.ByteString
      getKtvNetCodeBytes();

  /**
   * <pre>
   * 弹幕文本
   * </pre>
   *
   * <code>string text = 8;</code>
   */
  String getText();
  /**
   * <pre>
   * 弹幕文本
   * </pre>
   *
   * <code>string text = 8;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
