// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Node.proto

package com.bestarmedia.proto.node;

public interface BoxControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoxControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 设备ip 为空时则表示收到指令就要关机/重启
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  String getIp();
  /**
   * <pre>
   * 设备ip 为空时则表示收到指令就要关机/重启
   * </pre>
   *
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 0关机 1重启
   * </pre>
   *
   * <code>int32 op = 2;</code>
   */
  int getOp();

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 3;</code>
   */
  String getRoomCode();
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 3;</code>
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();
}
