// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Local.proto

package com.bestarmedia.proto.node;

public interface EvacuationLanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EvacuationLanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string ktv_net_code = 2;</code>
   */
  String getKtvNetCode();
  /**
   * <code>string ktv_net_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getKtvNetCodeBytes();

  /**
   * <code>int32 user_id = 3;</code>
   */
  int getUserId();

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 4;</code>
   */
  String getRoomCode();
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <pre>
   * 房间名
   * </pre>
   *
   * <code>string ktv_room_code = 5;</code>
   */
  String getKtvRoomCode();
  /**
   * <pre>
   * 房间名
   * </pre>
   *
   * <code>string ktv_room_code = 5;</code>
   */
  com.google.protobuf.ByteString
      getKtvRoomCodeBytes();

  /**
   * <pre>
   * base64 图片数据
   * </pre>
   *
   * <code>string image = 6;</code>
   */
  String getImage();
  /**
   * <pre>
   * base64 图片数据
   * </pre>
   *
   * <code>string image = 6;</code>
   */
  com.google.protobuf.ByteString
      getImageBytes();
}
