// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Local.proto

package com.bestarmedia.proto.node;

/**
 * <pre>
 * 火警素材回复
 * </pre>
 *
 * Protobuf type {@code FireAlarmMaterialResponse}
 */
public  final class FireAlarmMaterialResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FireAlarmMaterialResponse)
    FireAlarmMaterialResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireAlarmMaterialResponse.newBuilder() to construct.
  private FireAlarmMaterialResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireAlarmMaterialResponse() {
    alarmImgA_ = "";
    alarmImgB_ = "";
    address_ = "";
    ktvNetCode_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FireAlarmMaterialResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            alarmImgA_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            alarmImgB_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 32: {

            userId_ = input.readInt32();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            ktvNetCode_ = s;
            break;
          }
          case 48: {

            earlyAlarmTime_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bestarmedia.proto.node.LocalProto.internal_static_FireAlarmMaterialResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bestarmedia.proto.node.LocalProto.internal_static_FireAlarmMaterialResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FireAlarmMaterialResponse.class, Builder.class);
  }

  public static final int ALARM_IMG_A_FIELD_NUMBER = 1;
  private volatile Object alarmImgA_;
  /**
   * <pre>
   * 横版图 base64
   * </pre>
   *
   * <code>string alarm_img_a = 1;</code>
   */
  public String getAlarmImgA() {
    Object ref = alarmImgA_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      alarmImgA_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 横版图 base64
   * </pre>
   *
   * <code>string alarm_img_a = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAlarmImgABytes() {
    Object ref = alarmImgA_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      alarmImgA_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALARM_IMG_B_FIELD_NUMBER = 2;
  private volatile Object alarmImgB_;
  /**
   * <pre>
   * 竖版图 base 64
   * </pre>
   *
   * <code>string alarm_img_b = 2;</code>
   */
  public String getAlarmImgB() {
    Object ref = alarmImgB_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      alarmImgB_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 竖版图 base 64
   * </pre>
   *
   * <code>string alarm_img_b = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAlarmImgBBytes() {
    Object ref = alarmImgB_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      alarmImgB_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EARLY_ALARM_TIME_FIELD_NUMBER = 6;
  private int earlyAlarmTime_;
  /**
   * <pre>
   * 预警时间（分），默认为0
   * </pre>
   *
   * <code>int32 early_alarm_time = 6;</code>
   */
  public int getEarlyAlarmTime() {
    return earlyAlarmTime_;
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private volatile Object address_;
  /**
   * <code>string address = 3;</code>
   */
  public String getAddress() {
    Object ref = address_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAddressBytes() {
    Object ref = address_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 4;
  private int userId_;
  /**
   * <code>int32 user_id = 4;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int KTV_NET_CODE_FIELD_NUMBER = 5;
  private volatile Object ktvNetCode_;
  /**
   * <code>string ktv_net_code = 5;</code>
   */
  public String getKtvNetCode() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvNetCode_ = s;
      return s;
    }
  }
  /**
   * <code>string ktv_net_code = 5;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNetCodeBytes() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAlarmImgABytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alarmImgA_);
    }
    if (!getAlarmImgBBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, alarmImgB_);
    }
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
    }
    if (userId_ != 0) {
      output.writeInt32(4, userId_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ktvNetCode_);
    }
    if (earlyAlarmTime_ != 0) {
      output.writeInt32(6, earlyAlarmTime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAlarmImgABytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alarmImgA_);
    }
    if (!getAlarmImgBBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, alarmImgB_);
    }
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, userId_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ktvNetCode_);
    }
    if (earlyAlarmTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, earlyAlarmTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FireAlarmMaterialResponse)) {
      return super.equals(obj);
    }
    FireAlarmMaterialResponse other = (FireAlarmMaterialResponse) obj;

    if (!getAlarmImgA()
        .equals(other.getAlarmImgA())) return false;
    if (!getAlarmImgB()
        .equals(other.getAlarmImgB())) return false;
    if (getEarlyAlarmTime()
        != other.getEarlyAlarmTime()) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getKtvNetCode()
        .equals(other.getKtvNetCode())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALARM_IMG_A_FIELD_NUMBER;
    hash = (53 * hash) + getAlarmImgA().hashCode();
    hash = (37 * hash) + ALARM_IMG_B_FIELD_NUMBER;
    hash = (53 * hash) + getAlarmImgB().hashCode();
    hash = (37 * hash) + EARLY_ALARM_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getEarlyAlarmTime();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvNetCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FireAlarmMaterialResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FireAlarmMaterialResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FireAlarmMaterialResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FireAlarmMaterialResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FireAlarmMaterialResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FireAlarmMaterialResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FireAlarmMaterialResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FireAlarmMaterialResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FireAlarmMaterialResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FireAlarmMaterialResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FireAlarmMaterialResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FireAlarmMaterialResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FireAlarmMaterialResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 火警素材回复
   * </pre>
   *
   * Protobuf type {@code FireAlarmMaterialResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FireAlarmMaterialResponse)
      com.bestarmedia.proto.node.FireAlarmMaterialResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_FireAlarmMaterialResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_FireAlarmMaterialResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FireAlarmMaterialResponse.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.node.FireAlarmMaterialResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      alarmImgA_ = "";

      alarmImgB_ = "";

      earlyAlarmTime_ = 0;

      address_ = "";

      userId_ = 0;

      ktvNetCode_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_FireAlarmMaterialResponse_descriptor;
    }

    @Override
    public FireAlarmMaterialResponse getDefaultInstanceForType() {
      return FireAlarmMaterialResponse.getDefaultInstance();
    }

    @Override
    public FireAlarmMaterialResponse build() {
      FireAlarmMaterialResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FireAlarmMaterialResponse buildPartial() {
      FireAlarmMaterialResponse result = new FireAlarmMaterialResponse(this);
      result.alarmImgA_ = alarmImgA_;
      result.alarmImgB_ = alarmImgB_;
      result.earlyAlarmTime_ = earlyAlarmTime_;
      result.address_ = address_;
      result.userId_ = userId_;
      result.ktvNetCode_ = ktvNetCode_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FireAlarmMaterialResponse) {
        return mergeFrom((FireAlarmMaterialResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FireAlarmMaterialResponse other) {
      if (other == FireAlarmMaterialResponse.getDefaultInstance()) return this;
      if (!other.getAlarmImgA().isEmpty()) {
        alarmImgA_ = other.alarmImgA_;
        onChanged();
      }
      if (!other.getAlarmImgB().isEmpty()) {
        alarmImgB_ = other.alarmImgB_;
        onChanged();
      }
      if (other.getEarlyAlarmTime() != 0) {
        setEarlyAlarmTime(other.getEarlyAlarmTime());
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getKtvNetCode().isEmpty()) {
        ktvNetCode_ = other.ktvNetCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FireAlarmMaterialResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FireAlarmMaterialResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object alarmImgA_ = "";
    /**
     * <pre>
     * 横版图 base64
     * </pre>
     *
     * <code>string alarm_img_a = 1;</code>
     */
    public String getAlarmImgA() {
      Object ref = alarmImgA_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        alarmImgA_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 横版图 base64
     * </pre>
     *
     * <code>string alarm_img_a = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAlarmImgABytes() {
      Object ref = alarmImgA_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        alarmImgA_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 横版图 base64
     * </pre>
     *
     * <code>string alarm_img_a = 1;</code>
     */
    public Builder setAlarmImgA(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alarmImgA_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 横版图 base64
     * </pre>
     *
     * <code>string alarm_img_a = 1;</code>
     */
    public Builder clearAlarmImgA() {
      
      alarmImgA_ = getDefaultInstance().getAlarmImgA();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 横版图 base64
     * </pre>
     *
     * <code>string alarm_img_a = 1;</code>
     */
    public Builder setAlarmImgABytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alarmImgA_ = value;
      onChanged();
      return this;
    }

    private Object alarmImgB_ = "";
    /**
     * <pre>
     * 竖版图 base 64
     * </pre>
     *
     * <code>string alarm_img_b = 2;</code>
     */
    public String getAlarmImgB() {
      Object ref = alarmImgB_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        alarmImgB_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 竖版图 base 64
     * </pre>
     *
     * <code>string alarm_img_b = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAlarmImgBBytes() {
      Object ref = alarmImgB_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        alarmImgB_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 竖版图 base 64
     * </pre>
     *
     * <code>string alarm_img_b = 2;</code>
     */
    public Builder setAlarmImgB(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alarmImgB_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 竖版图 base 64
     * </pre>
     *
     * <code>string alarm_img_b = 2;</code>
     */
    public Builder clearAlarmImgB() {
      
      alarmImgB_ = getDefaultInstance().getAlarmImgB();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 竖版图 base 64
     * </pre>
     *
     * <code>string alarm_img_b = 2;</code>
     */
    public Builder setAlarmImgBBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alarmImgB_ = value;
      onChanged();
      return this;
    }

    private int earlyAlarmTime_ ;
    /**
     * <pre>
     * 预警时间（分），默认为0
     * </pre>
     *
     * <code>int32 early_alarm_time = 6;</code>
     */
    public int getEarlyAlarmTime() {
      return earlyAlarmTime_;
    }
    /**
     * <pre>
     * 预警时间（分），默认为0
     * </pre>
     *
     * <code>int32 early_alarm_time = 6;</code>
     */
    public Builder setEarlyAlarmTime(int value) {
      
      earlyAlarmTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 预警时间（分），默认为0
     * </pre>
     *
     * <code>int32 early_alarm_time = 6;</code>
     */
    public Builder clearEarlyAlarmTime() {
      
      earlyAlarmTime_ = 0;
      onChanged();
      return this;
    }

    private Object address_ = "";
    /**
     * <code>string address = 3;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 3;</code>
     */
    public Builder setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 3;</code>
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 3;</code>
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 4;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 4;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 4;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private Object ktvNetCode_ = "";
    /**
     * <code>string ktv_net_code = 5;</code>
     */
    public String getKtvNetCode() {
      Object ref = ktvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 5;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNetCodeBytes() {
      Object ref = ktvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 5;</code>
     */
    public Builder setKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 5;</code>
     */
    public Builder clearKtvNetCode() {
      
      ktvNetCode_ = getDefaultInstance().getKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 5;</code>
     */
    public Builder setKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FireAlarmMaterialResponse)
  }

  // @@protoc_insertion_point(class_scope:FireAlarmMaterialResponse)
  private static final FireAlarmMaterialResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FireAlarmMaterialResponse();
  }

  public static FireAlarmMaterialResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FireAlarmMaterialResponse>
      PARSER = new com.google.protobuf.AbstractParser<FireAlarmMaterialResponse>() {
    @Override
    public FireAlarmMaterialResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FireAlarmMaterialResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FireAlarmMaterialResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FireAlarmMaterialResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public FireAlarmMaterialResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

