// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Local.proto

package com.bestarmedia.proto.node;

/**
 * <pre>
 * 走马灯列表请求
 * </pre>
 *
 * Protobuf type {@code LocalNoticeRequest}
 */
public  final class LocalNoticeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LocalNoticeRequest)
    LocalNoticeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocalNoticeRequest.newBuilder() to construct.
  private LocalNoticeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocalNoticeRequest() {
    address_ = "";
    ktvNetCode_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocalNoticeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 16: {

            userId_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            ktvNetCode_ = s;
            break;
          }
          case 32: {

            circleType_ = input.readInt32();
            break;
          }
          case 40: {

            currentPage_ = input.readInt32();
            break;
          }
          case 48: {

            perPage_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bestarmedia.proto.node.LocalProto.internal_static_LocalNoticeRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bestarmedia.proto.node.LocalProto.internal_static_LocalNoticeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LocalNoticeRequest.class, Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private volatile Object address_;
  /**
   * <code>string address = 1;</code>
   */
  public String getAddress() {
    Object ref = address_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAddressBytes() {
    Object ref = address_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private int userId_;
  /**
   * <code>int32 user_id = 2;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int KTV_NET_CODE_FIELD_NUMBER = 3;
  private volatile Object ktvNetCode_;
  /**
   * <code>string ktv_net_code = 3;</code>
   */
  public String getKtvNetCode() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvNetCode_ = s;
      return s;
    }
  }
  /**
   * <code>string ktv_net_code = 3;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNetCodeBytes() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CIRCLE_TYPE_FIELD_NUMBER = 4;
  private int circleType_;
  /**
   * <pre>
   * 循环方式 1定时 2即时
   * </pre>
   *
   * <code>int32 circle_type = 4;</code>
   */
  public int getCircleType() {
    return circleType_;
  }

  public static final int CURRENT_PAGE_FIELD_NUMBER = 5;
  private int currentPage_;
  /**
   * <code>int32 current_page = 5;</code>
   */
  public int getCurrentPage() {
    return currentPage_;
  }

  public static final int PER_PAGE_FIELD_NUMBER = 6;
  private int perPage_;
  /**
   * <code>int32 per_page = 6;</code>
   */
  public int getPerPage() {
    return perPage_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
    }
    if (userId_ != 0) {
      output.writeInt32(2, userId_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ktvNetCode_);
    }
    if (circleType_ != 0) {
      output.writeInt32(4, circleType_);
    }
    if (currentPage_ != 0) {
      output.writeInt32(5, currentPage_);
    }
    if (perPage_ != 0) {
      output.writeInt32(6, perPage_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, userId_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ktvNetCode_);
    }
    if (circleType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, circleType_);
    }
    if (currentPage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, currentPage_);
    }
    if (perPage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, perPage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LocalNoticeRequest)) {
      return super.equals(obj);
    }
    LocalNoticeRequest other = (LocalNoticeRequest) obj;

    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getKtvNetCode()
        .equals(other.getKtvNetCode())) return false;
    if (getCircleType()
        != other.getCircleType()) return false;
    if (getCurrentPage()
        != other.getCurrentPage()) return false;
    if (getPerPage()
        != other.getPerPage()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvNetCode().hashCode();
    hash = (37 * hash) + CIRCLE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCircleType();
    hash = (37 * hash) + CURRENT_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPage();
    hash = (37 * hash) + PER_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPerPage();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LocalNoticeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LocalNoticeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LocalNoticeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LocalNoticeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LocalNoticeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LocalNoticeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LocalNoticeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LocalNoticeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LocalNoticeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LocalNoticeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LocalNoticeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LocalNoticeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LocalNoticeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 走马灯列表请求
   * </pre>
   *
   * Protobuf type {@code LocalNoticeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LocalNoticeRequest)
      com.bestarmedia.proto.node.LocalNoticeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_LocalNoticeRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_LocalNoticeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LocalNoticeRequest.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.node.LocalNoticeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      address_ = "";

      userId_ = 0;

      ktvNetCode_ = "";

      circleType_ = 0;

      currentPage_ = 0;

      perPage_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bestarmedia.proto.node.LocalProto.internal_static_LocalNoticeRequest_descriptor;
    }

    @Override
    public LocalNoticeRequest getDefaultInstanceForType() {
      return LocalNoticeRequest.getDefaultInstance();
    }

    @Override
    public LocalNoticeRequest build() {
      LocalNoticeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LocalNoticeRequest buildPartial() {
      LocalNoticeRequest result = new LocalNoticeRequest(this);
      result.address_ = address_;
      result.userId_ = userId_;
      result.ktvNetCode_ = ktvNetCode_;
      result.circleType_ = circleType_;
      result.currentPage_ = currentPage_;
      result.perPage_ = perPage_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LocalNoticeRequest) {
        return mergeFrom((LocalNoticeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LocalNoticeRequest other) {
      if (other == LocalNoticeRequest.getDefaultInstance()) return this;
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getKtvNetCode().isEmpty()) {
        ktvNetCode_ = other.ktvNetCode_;
        onChanged();
      }
      if (other.getCircleType() != 0) {
        setCircleType(other.getCircleType());
      }
      if (other.getCurrentPage() != 0) {
        setCurrentPage(other.getCurrentPage());
      }
      if (other.getPerPage() != 0) {
        setPerPage(other.getPerPage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LocalNoticeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LocalNoticeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object address_ = "";
    /**
     * <code>string address = 1;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 1;</code>
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 2;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 2;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private Object ktvNetCode_ = "";
    /**
     * <code>string ktv_net_code = 3;</code>
     */
    public String getKtvNetCode() {
      Object ref = ktvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNetCodeBytes() {
      Object ref = ktvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 3;</code>
     */
    public Builder setKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 3;</code>
     */
    public Builder clearKtvNetCode() {
      
      ktvNetCode_ = getDefaultInstance().getKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 3;</code>
     */
    public Builder setKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvNetCode_ = value;
      onChanged();
      return this;
    }

    private int circleType_ ;
    /**
     * <pre>
     * 循环方式 1定时 2即时
     * </pre>
     *
     * <code>int32 circle_type = 4;</code>
     */
    public int getCircleType() {
      return circleType_;
    }
    /**
     * <pre>
     * 循环方式 1定时 2即时
     * </pre>
     *
     * <code>int32 circle_type = 4;</code>
     */
    public Builder setCircleType(int value) {
      
      circleType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 循环方式 1定时 2即时
     * </pre>
     *
     * <code>int32 circle_type = 4;</code>
     */
    public Builder clearCircleType() {
      
      circleType_ = 0;
      onChanged();
      return this;
    }

    private int currentPage_ ;
    /**
     * <code>int32 current_page = 5;</code>
     */
    public int getCurrentPage() {
      return currentPage_;
    }
    /**
     * <code>int32 current_page = 5;</code>
     */
    public Builder setCurrentPage(int value) {
      
      currentPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_page = 5;</code>
     */
    public Builder clearCurrentPage() {
      
      currentPage_ = 0;
      onChanged();
      return this;
    }

    private int perPage_ ;
    /**
     * <code>int32 per_page = 6;</code>
     */
    public int getPerPage() {
      return perPage_;
    }
    /**
     * <code>int32 per_page = 6;</code>
     */
    public Builder setPerPage(int value) {
      
      perPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 per_page = 6;</code>
     */
    public Builder clearPerPage() {
      
      perPage_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LocalNoticeRequest)
  }

  // @@protoc_insertion_point(class_scope:LocalNoticeRequest)
  private static final LocalNoticeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LocalNoticeRequest();
  }

  public static LocalNoticeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocalNoticeRequest>
      PARSER = new com.google.protobuf.AbstractParser<LocalNoticeRequest>() {
    @Override
    public LocalNoticeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocalNoticeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocalNoticeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LocalNoticeRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public LocalNoticeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

