// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Local.proto

package com.bestarmedia.proto.node;

public interface LocalNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocalNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 order = 2;</code>
   */
  int getOrder();

  /**
   * <code>int32 circle_type = 3;</code>
   */
  int getCircleType();

  /**
   * <code>int32 is_everyday_play = 4;</code>
   */
  int getIsEverydayPlay();

  /**
   * <code>string start_date = 5;</code>
   */
  String getStartDate();
  /**
   * <code>string start_date = 5;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string font_color = 6;</code>
   */
  String getFontColor();
  /**
   * <code>string font_color = 6;</code>
   */
  com.google.protobuf.ByteString
      getFontColorBytes();

  /**
   * <code>int32 status = 7;</code>
   */
  int getStatus();

  /**
   * <code>int32 play_type = 8;</code>
   */
  int getPlayType();

  /**
   * <code>int32 times = 9;</code>
   */
  int getTimes();

  /**
   * <code>string start_time = 10;</code>
   */
  String getStartTime();
  /**
   * <code>string start_time = 10;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string end_time = 11;</code>
   */
  String getEndTime();
  /**
   * <code>string end_time = 11;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();

  /**
   * <code>string created_at = 12;</code>
   */
  String getCreatedAt();
  /**
   * <code>string created_at = 12;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string updated_at = 13;</code>
   */
  String getUpdatedAt();
  /**
   * <code>string updated_at = 13;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();

  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .LocalNoticeRoom room_list = 14;</code>
   */
  java.util.List<com.bestarmedia.proto.node.LocalNoticeRoom> 
      getRoomListList();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .LocalNoticeRoom room_list = 14;</code>
   */
  com.bestarmedia.proto.node.LocalNoticeRoom getRoomList(int index);
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .LocalNoticeRoom room_list = 14;</code>
   */
  int getRoomListCount();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .LocalNoticeRoom room_list = 14;</code>
   */
  java.util.List<? extends com.bestarmedia.proto.node.LocalNoticeRoomOrBuilder> 
      getRoomListOrBuilderList();
  /**
   * <pre>
   * 房间列表
   * </pre>
   *
   * <code>repeated .LocalNoticeRoom room_list = 14;</code>
   */
  com.bestarmedia.proto.node.LocalNoticeRoomOrBuilder getRoomListOrBuilder(
          int index);
}
