// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Local.proto

package com.bestarmedia.proto.node;

public interface LocalNoticeRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocalNoticeRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 user_id = 2;</code>
   */
  int getUserId();

  /**
   * <code>string ktv_net_code = 3;</code>
   */
  String getKtvNetCode();
  /**
   * <code>string ktv_net_code = 3;</code>
   */
  com.google.protobuf.ByteString
      getKtvNetCodeBytes();

  /**
   * <code>int32 current_page = 5;</code>
   */
  int getCurrentPage();

  /**
   * <code>int32 per_page = 6;</code>
   */
  int getPerPage();

  /**
   * <code>string start_date = 7;</code>
   */
  String getStartDate();
  /**
   * <code>string start_date = 7;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string end_date = 8;</code>
   */
  String getEndDate();
  /**
   * <code>string end_date = 8;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
