// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Node.proto

package com.bestarmedia.proto.node;

public interface PayMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PayMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ktv_net_code = 1;</code>
   */
  String getKtvNetCode();
  /**
   * <code>string ktv_net_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getKtvNetCodeBytes();

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 2;</code>
   */
  String getRoomCode();
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <pre>
   * 支付二维码
   * </pre>
   *
   * <code>string pay_url = 3;</code>
   */
  String getPayUrl();
  /**
   * <pre>
   * 支付二维码
   * </pre>
   *
   * <code>string pay_url = 3;</code>
   */
  com.google.protobuf.ByteString
      getPayUrlBytes();
}
