// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mime.proto

package com.bestarmedia.proto.node;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   */
  String getContent();
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 颜色值 #FFFFFFFF
   * </pre>
   *
   * <code>string color = 2;</code>
   */
  String getColor();
  /**
   * <pre>
   * 颜色值 #FFFFFFFF
   * </pre>
   *
   * <code>string color = 2;</code>
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <pre>
   * 背景图 url 默认为空值
   * </pre>
   *
   * <code>string background = 3;</code>
   */
  String getBackground();
  /**
   * <pre>
   * 背景图 url 默认为空值
   * </pre>
   *
   * <code>string background = 3;</code>
   */
  com.google.protobuf.ByteString
      getBackgroundBytes();

  /**
   * <pre>
   * 屏幕左边的x坐标 默认0,
   * </pre>
   *
   * <code>int32 left_x = 4;</code>
   */
  int getLeftX();

  /**
   * <pre>
   * 屏幕右边的y坐标 默认720
   * </pre>
   *
   * <code>int32 right_x = 5;</code>
   */
  int getRightX();

  /**
   * <pre>
   * 高度Y坐标 默认80（走马灯顶部）
   * </pre>
   *
   * <code>int32 y = 6;</code>
   */
  int getY();

  /**
   * <pre>
   * 单条播放时长，默认30s
   * </pre>
   *
   * <code>int32 play_time = 7;</code>
   */
  int getPlayTime();

  /**
   * <pre>
   * 播放次数 默认 1次
   * </pre>
   *
   * <code>int32 play_count = 9;</code>
   */
  int getPlayCount();

  /**
   * <pre>
   * 播放间隔时间 单位秒，默认15秒
   * </pre>
   *
   * <code>int32 play_interval = 10;</code>
   */
  int getPlayInterval();

  /**
   * <pre>
   * 播放方向 1 从右向左 2从左向右，默认1
   * </pre>
   *
   * <code>int32 play_direction = 11;</code>
   */
  int getPlayDirection();

  /**
   * <pre>
   * 0 店家本地 1 政府监管
   * </pre>
   *
   * <code>int32 source = 12;</code>
   */
  int getSource();
}
