// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mime.proto

package com.bestarmedia.proto.node;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 出现方式 1单通道 2双通道
   * </pre>
   *
   * <code>int32 type = 1;</code>
   */
  int getType();

  /**
   * <pre>
   * 播放方式 1即时播放 2歌曲结束后播放
   * </pre>
   *
   * <code>int32 play_type = 11;</code>
   */
  int getPlayType();

  /**
   * <pre>
   * 视频 url
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  String getUrl();
  /**
   * <pre>
   * 视频 url
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 图片
   * </pre>
   *
   * <code>.Image image = 9;</code>
   */
  boolean hasImage();
  /**
   * <pre>
   * 图片
   * </pre>
   *
   * <code>.Image image = 9;</code>
   */
  Image getImage();
  /**
   * <pre>
   * 图片
   * </pre>
   *
   * <code>.Image image = 9;</code>
   */
  ImageOrBuilder getImageOrBuilder();

  /**
   * <pre>
   * 以下字段在单通道方式需要
   * </pre>
   *
   * <code>int32 width = 3;</code>
   */
  int getWidth();

  /**
   * <pre>
   * 视频窗口高，默认屏幕高度1/3=240
   * </pre>
   *
   * <code>int32 height = 4;</code>
   */
  int getHeight();

  /**
   * <pre>
   * 开始位置X坐标，默认0
   * </pre>
   *
   * <code>int32 start_x = 5;</code>
   */
  int getStartX();

  /**
   * <pre>
   * 开始位置Y坐标 默认0
   * </pre>
   *
   * <code>int32 start_y = 6;</code>
   */
  int getStartY();

  /**
   * <pre>
   * 结束位置X坐标，默认426（居中显示）
   * </pre>
   *
   * <code>int32 end_x = 7;</code>
   */
  int getEndX();

  /**
   * <pre>
   * 结束位置Y坐标 默认240（居中显示）
   * </pre>
   *
   * <code>int32 end_y = 8;</code>
   */
  int getEndY();

  /**
   * <pre>
   * 0 店家本地 1 政府管理
   * </pre>
   *
   * <code>int32 source = 10;</code>
   */
  int getSource();
}
