// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Node.proto

package com.bestarmedia.proto.node;

/**
 * <pre>
 * 升/降音量请求
 * </pre>
 *
 * Protobuf type {@code VolumeRequest}
 */
public  final class VolumeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:VolumeRequest)
    VolumeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VolumeRequest.newBuilder() to construct.
  private VolumeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VolumeRequest() {
    roomCode_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VolumeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            roomCode_ = s;
            break;
          }
          case 16: {

            op_ = input.readInt32();
            break;
          }
          case 24: {

            volume_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NodeProto.internal_static_VolumeRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NodeProto.internal_static_VolumeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            VolumeRequest.class, Builder.class);
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 1;
  private volatile Object roomCode_;
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 1;</code>
   */
  public String getRoomCode() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OP_FIELD_NUMBER = 2;
  private int op_;
  /**
   * <pre>
   * 1降音量 2升音量
   * </pre>
   *
   * <code>int32 op = 2;</code>
   */
  public int getOp() {
    return op_;
  }

  public static final int VOLUME_FIELD_NUMBER = 3;
  private int volume_;
  /**
   * <code>int32 volume = 3;</code>
   */
  public int getVolume() {
    return volume_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomCode_);
    }
    if (op_ != 0) {
      output.writeInt32(2, op_);
    }
    if (volume_ != 0) {
      output.writeInt32(3, volume_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomCode_);
    }
    if (op_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, op_);
    }
    if (volume_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, volume_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof VolumeRequest)) {
      return super.equals(obj);
    }
    VolumeRequest other = (VolumeRequest) obj;

    if (!getRoomCode()
        .equals(other.getRoomCode())) return false;
    if (getOp()
        != other.getOp()) return false;
    if (getVolume()
        != other.getVolume()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoomCode().hashCode();
    hash = (37 * hash) + OP_FIELD_NUMBER;
    hash = (53 * hash) + getOp();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getVolume();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VolumeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VolumeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VolumeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VolumeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VolumeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static VolumeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static VolumeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VolumeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static VolumeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static VolumeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static VolumeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static VolumeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(VolumeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 升/降音量请求
   * </pre>
   *
   * Protobuf type {@code VolumeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:VolumeRequest)
      com.bestarmedia.proto.node.VolumeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeProto.internal_static_VolumeRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeProto.internal_static_VolumeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VolumeRequest.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.node.VolumeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      roomCode_ = "";

      op_ = 0;

      volume_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NodeProto.internal_static_VolumeRequest_descriptor;
    }

    @Override
    public VolumeRequest getDefaultInstanceForType() {
      return VolumeRequest.getDefaultInstance();
    }

    @Override
    public VolumeRequest build() {
      VolumeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VolumeRequest buildPartial() {
      VolumeRequest result = new VolumeRequest(this);
      result.roomCode_ = roomCode_;
      result.op_ = op_;
      result.volume_ = volume_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VolumeRequest) {
        return mergeFrom((VolumeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VolumeRequest other) {
      if (other == VolumeRequest.getDefaultInstance()) return this;
      if (!other.getRoomCode().isEmpty()) {
        roomCode_ = other.roomCode_;
        onChanged();
      }
      if (other.getOp() != 0) {
        setOp(other.getOp());
      }
      if (other.getVolume() != 0) {
        setVolume(other.getVolume());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VolumeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VolumeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object roomCode_ = "";
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 1;</code>
     */
    public String getRoomCode() {
      Object ref = roomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 1;</code>
     */
    public Builder setRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 1;</code>
     */
    public Builder clearRoomCode() {
      
      roomCode_ = getDefaultInstance().getRoomCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 1;</code>
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomCode_ = value;
      onChanged();
      return this;
    }

    private int op_ ;
    /**
     * <pre>
     * 1降音量 2升音量
     * </pre>
     *
     * <code>int32 op = 2;</code>
     */
    public int getOp() {
      return op_;
    }
    /**
     * <pre>
     * 1降音量 2升音量
     * </pre>
     *
     * <code>int32 op = 2;</code>
     */
    public Builder setOp(int value) {
      
      op_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1降音量 2升音量
     * </pre>
     *
     * <code>int32 op = 2;</code>
     */
    public Builder clearOp() {
      
      op_ = 0;
      onChanged();
      return this;
    }

    private int volume_ ;
    /**
     * <code>int32 volume = 3;</code>
     */
    public int getVolume() {
      return volume_;
    }
    /**
     * <code>int32 volume = 3;</code>
     */
    public Builder setVolume(int value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 volume = 3;</code>
     */
    public Builder clearVolume() {
      
      volume_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:VolumeRequest)
  }

  // @@protoc_insertion_point(class_scope:VolumeRequest)
  private static final VolumeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VolumeRequest();
  }

  public static VolumeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VolumeRequest>
      PARSER = new com.google.protobuf.AbstractParser<VolumeRequest>() {
    @Override
    public VolumeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VolumeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VolumeRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VolumeRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public VolumeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

