// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notice.proto

package com.bestarmedia.proto.monitor;

/**
 * <pre>
 * 通知回复
 * </pre>
 *
 * Protobuf type {@code NoticeResponse}
 */
public  final class NoticeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NoticeResponse)
    NoticeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NoticeResponse.newBuilder() to construct.
  private NoticeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NoticeResponse() {
    ktvNetCode_ = "";
    roomCode_ = "";
    logId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NoticeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            ktvNetCode_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            roomCode_ = s;
            break;
          }
          case 24: {

            code_ = input.readInt32();
            break;
          }
          case 32: {

            noticeId_ = input.readInt64();
            break;
          }
          case 40: {

            type_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            logId_ = s;
            break;
          }
          case 56: {

            userId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NoticeProto.internal_static_NoticeResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NoticeProto.internal_static_NoticeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NoticeResponse.class, Builder.class);
  }

  public static final int KTV_NET_CODE_FIELD_NUMBER = 1;
  private volatile Object ktvNetCode_;
  /**
   * <code>string ktv_net_code = 1;</code>
   */
  public String getKtvNetCode() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvNetCode_ = s;
      return s;
    }
  }
  /**
   * <code>string ktv_net_code = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNetCodeBytes() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 2;
  private volatile Object roomCode_;
  /**
   * <code>string room_code = 2;</code>
   */
  public String getRoomCode() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <code>string room_code = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTICE_ID_FIELD_NUMBER = 4;
  private long noticeId_;
  /**
   * <pre>
   * 通知id
   * </pre>
   *
   * <code>int64 notice_id = 4;</code>
   */
  public long getNoticeId() {
    return noticeId_;
  }

  public static final int LOG_ID_FIELD_NUMBER = 6;
  private volatile Object logId_;
  /**
   * <pre>
   * 通知log id
   * </pre>
   *
   * <code>string log_id = 6;</code>
   */
  public String getLogId() {
    Object ref = logId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      logId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 通知log id
   * </pre>
   *
   * <code>string log_id = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLogIdBytes() {
    Object ref = logId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      logId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private int type_;
  /**
   * <pre>
   * 消息类型 1文本 2图文 3视频
   * </pre>
   *
   * <code>int32 type = 5;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int CODE_FIELD_NUMBER = 3;
  private int code_;
  /**
   * <pre>
   * 0失败 1成功
   * </pre>
   *
   * <code>int32 code = 3;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int USER_ID_FIELD_NUMBER = 7;
  private int userId_;
  /**
   * <pre>
   *用户id 可能来自手机或者本地功能或者远程监管
   * </pre>
   *
   * <code>int32 user_id = 7;</code>
   */
  public int getUserId() {
    return userId_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomCode_);
    }
    if (code_ != 0) {
      output.writeInt32(3, code_);
    }
    if (noticeId_ != 0L) {
      output.writeInt64(4, noticeId_);
    }
    if (type_ != 0) {
      output.writeInt32(5, type_);
    }
    if (!getLogIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, logId_);
    }
    if (userId_ != 0) {
      output.writeInt32(7, userId_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomCode_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, code_);
    }
    if (noticeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, noticeId_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, type_);
    }
    if (!getLogIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, logId_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, userId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NoticeResponse)) {
      return super.equals(obj);
    }
    NoticeResponse other = (NoticeResponse) obj;

    if (!getKtvNetCode()
        .equals(other.getKtvNetCode())) return false;
    if (!getRoomCode()
        .equals(other.getRoomCode())) return false;
    if (getNoticeId()
        != other.getNoticeId()) return false;
    if (!getLogId()
        .equals(other.getLogId())) return false;
    if (getType()
        != other.getType()) return false;
    if (getCode()
        != other.getCode()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvNetCode().hashCode();
    hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoomCode().hashCode();
    hash = (37 * hash) + NOTICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNoticeId());
    hash = (37 * hash) + LOG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLogId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NoticeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NoticeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NoticeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NoticeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NoticeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NoticeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NoticeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NoticeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NoticeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NoticeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NoticeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NoticeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NoticeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 通知回复
   * </pre>
   *
   * Protobuf type {@code NoticeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NoticeResponse)
      com.bestarmedia.proto.monitor.NoticeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NoticeProto.internal_static_NoticeResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NoticeProto.internal_static_NoticeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NoticeResponse.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.monitor.NoticeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      ktvNetCode_ = "";

      roomCode_ = "";

      noticeId_ = 0L;

      logId_ = "";

      type_ = 0;

      code_ = 0;

      userId_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NoticeProto.internal_static_NoticeResponse_descriptor;
    }

    @Override
    public NoticeResponse getDefaultInstanceForType() {
      return NoticeResponse.getDefaultInstance();
    }

    @Override
    public NoticeResponse build() {
      NoticeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NoticeResponse buildPartial() {
      NoticeResponse result = new NoticeResponse(this);
      result.ktvNetCode_ = ktvNetCode_;
      result.roomCode_ = roomCode_;
      result.noticeId_ = noticeId_;
      result.logId_ = logId_;
      result.type_ = type_;
      result.code_ = code_;
      result.userId_ = userId_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NoticeResponse) {
        return mergeFrom((NoticeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NoticeResponse other) {
      if (other == NoticeResponse.getDefaultInstance()) return this;
      if (!other.getKtvNetCode().isEmpty()) {
        ktvNetCode_ = other.ktvNetCode_;
        onChanged();
      }
      if (!other.getRoomCode().isEmpty()) {
        roomCode_ = other.roomCode_;
        onChanged();
      }
      if (other.getNoticeId() != 0L) {
        setNoticeId(other.getNoticeId());
      }
      if (!other.getLogId().isEmpty()) {
        logId_ = other.logId_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NoticeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NoticeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object ktvNetCode_ = "";
    /**
     * <code>string ktv_net_code = 1;</code>
     */
    public String getKtvNetCode() {
      Object ref = ktvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNetCodeBytes() {
      Object ref = ktvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder setKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder clearKtvNetCode() {
      
      ktvNetCode_ = getDefaultInstance().getKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <code>string ktv_net_code = 1;</code>
     */
    public Builder setKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvNetCode_ = value;
      onChanged();
      return this;
    }

    private Object roomCode_ = "";
    /**
     * <code>string room_code = 2;</code>
     */
    public String getRoomCode() {
      Object ref = roomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string room_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string room_code = 2;</code>
     */
    public Builder setRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string room_code = 2;</code>
     */
    public Builder clearRoomCode() {
      
      roomCode_ = getDefaultInstance().getRoomCode();
      onChanged();
      return this;
    }
    /**
     * <code>string room_code = 2;</code>
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomCode_ = value;
      onChanged();
      return this;
    }

    private long noticeId_ ;
    /**
     * <pre>
     * 通知id
     * </pre>
     *
     * <code>int64 notice_id = 4;</code>
     */
    public long getNoticeId() {
      return noticeId_;
    }
    /**
     * <pre>
     * 通知id
     * </pre>
     *
     * <code>int64 notice_id = 4;</code>
     */
    public Builder setNoticeId(long value) {
      
      noticeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知id
     * </pre>
     *
     * <code>int64 notice_id = 4;</code>
     */
    public Builder clearNoticeId() {
      
      noticeId_ = 0L;
      onChanged();
      return this;
    }

    private Object logId_ = "";
    /**
     * <pre>
     * 通知log id
     * </pre>
     *
     * <code>string log_id = 6;</code>
     */
    public String getLogId() {
      Object ref = logId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 通知log id
     * </pre>
     *
     * <code>string log_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      Object ref = logId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 通知log id
     * </pre>
     *
     * <code>string log_id = 6;</code>
     */
    public Builder setLogId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知log id
     * </pre>
     *
     * <code>string log_id = 6;</code>
     */
    public Builder clearLogId() {
      
      logId_ = getDefaultInstance().getLogId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通知log id
     * </pre>
     *
     * <code>string log_id = 6;</code>
     */
    public Builder setLogIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      logId_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     * 消息类型 1文本 2图文 3视频
     * </pre>
     *
     * <code>int32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型 1文本 2图文 3视频
     * </pre>
     *
     * <code>int32 type = 5;</code>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型 1文本 2图文 3视频
     * </pre>
     *
     * <code>int32 type = 5;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <pre>
     * 0失败 1成功
     * </pre>
     *
     * <code>int32 code = 3;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     * 0失败 1成功
     * </pre>
     *
     * <code>int32 code = 3;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0失败 1成功
     * </pre>
     *
     * <code>int32 code = 3;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <pre>
     *用户id 可能来自手机或者本地功能或者远程监管
     * </pre>
     *
     * <code>int32 user_id = 7;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <pre>
     *用户id 可能来自手机或者本地功能或者远程监管
     * </pre>
     *
     * <code>int32 user_id = 7;</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户id 可能来自手机或者本地功能或者远程监管
     * </pre>
     *
     * <code>int32 user_id = 7;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NoticeResponse)
  }

  // @@protoc_insertion_point(class_scope:NoticeResponse)
  private static final NoticeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NoticeResponse();
  }

  public static NoticeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NoticeResponse>
      PARSER = new com.google.protobuf.AbstractParser<NoticeResponse>() {
    @Override
    public NoticeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NoticeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NoticeResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NoticeResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public NoticeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

