// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Monitor.proto

package com.bestarmedia.proto.monitor;

public interface StreamMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息类型 0其它 1营业 2火警 3异常行为 4点歌
   * </pre>
   *
   * <code>int32 type = 1;</code>
   */
  int getType();

  /**
   * <pre>
   * 子消息类型
   * </pre>
   *
   * <code>int32 sub_type = 2;</code>
   */
  int getSubType();

  /**
   * <pre>
   * 消息发生时间
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  String getDate();
  /**
   * <pre>
   * 消息发生时间
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 4;</code>
   */
  String getKtvNetCode();
  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getKtvNetCodeBytes();

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 5;</code>
   */
  String getRoomCode();
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoomCodeBytes();

  /**
   * <pre>
   * KTV房间名
   * </pre>
   *
   * <code>string ktv_room_code = 9;</code>
   */
  String getKtvRoomCode();
  /**
   * <pre>
   * KTV房间名
   * </pre>
   *
   * <code>string ktv_room_code = 9;</code>
   */
  com.google.protobuf.ByteString
      getKtvRoomCodeBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 6;</code>
   */
  String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 6;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 扩展内容（备用）
   * </pre>
   *
   * <code>string extra = 7;</code>
   */
  String getExtra();
  /**
   * <pre>
   * 扩展内容（备用）
   * </pre>
   *
   * <code>string extra = 7;</code>
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <pre>
   * KTV名称
   * </pre>
   *
   * <code>string ktv_name = 8;</code>
   */
  String getKtvName();
  /**
   * <pre>
   * KTV名称
   * </pre>
   *
   * <code>string ktv_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getKtvNameBytes();
}
