// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Monitor.proto

package com.bestarmedia.proto.monitor;

/**
 * <pre>
 * 流水消息
 * </pre>
 *
 * Protobuf type {@code StreamMessage}
 */
public  final class StreamMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamMessage)
    StreamMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamMessage.newBuilder() to construct.
  private StreamMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamMessage() {
    date_ = "";
    ktvNetCode_ = "";
    roomCode_ = "";
    ktvRoomCode_ = "";
    content_ = "";
    extra_ = "";
    ktvName_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            type_ = input.readInt32();
            break;
          }
          case 16: {

            subType_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            ktvNetCode_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            roomCode_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            content_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            extra_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            ktvName_ = s;
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();

            ktvRoomCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MonitorProto.internal_static_StreamMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MonitorProto.internal_static_StreamMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StreamMessage.class, Builder.class);
  }

  /**
   * Protobuf enum {@code StreamMessage.SubType}
   */
  public enum SubType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 其它
     * </pre>
     *
     * <code>ELSE = 0;</code>
     */
    ELSE(0),
    /**
     * <pre>
     * 开房
     * </pre>
     *
     * <code>ROOM_OPEN = 1;</code>
     */
    ROOM_OPEN(1),
    /**
     * <pre>
     * 关房
     * </pre>
     *
     * <code>ROOM_CLOSE = 2;</code>
     */
    ROOM_CLOSE(2),
    /**
     * <pre>
     * 机顶盒上线
     * </pre>
     *
     * <code>BOX_ONLINE = 3;</code>
     */
    BOX_ONLINE(3),
    /**
     * <pre>
     * 机顶盒下线
     * </pre>
     *
     * <code>BOX_OFFLINE = 4;</code>
     */
    BOX_OFFLINE(4),
    /**
     * <pre>
     * 服务器上线
     * </pre>
     *
     * <code>NODE_ONLINE = 5;</code>
     */
    NODE_ONLINE(5),
    /**
     * <pre>
     * 服务器下线
     * </pre>
     *
     * <code>NODE_OFFLINE = 6;</code>
     */
    NODE_OFFLINE(6),
    /**
     * <pre>
     * 火警预警
     * </pre>
     *
     * <code>EARLY_FIRE_ALARM = 7;</code>
     */
    EARLY_FIRE_ALARM(7),
    /**
     * <pre>
     * 火警 （此时需要将火警信号发给房间客人）
     * </pre>
     *
     * <code>FIRE_ALARM = 8;</code>
     */
    FIRE_ALARM(8),
    /**
     * <pre>
     * 疑似吸毒
     * </pre>
     *
     * <code>DRUG = 9;</code>
     */
    DRUG(9),
    /**
     * <pre>
     * 疑似未成年人
     * </pre>
     *
     * <code>MINORS = 10;</code>
     */
    MINORS(10),
    /**
     * <pre>
     * 点歌
     * </pre>
     *
     * <code>SONG = 11;</code>
     */
    SONG(11),
    /**
     * <pre>
     * 火警取消
     * </pre>
     *
     * <code>FIRE_ALARM_CANCEL = 12;</code>
     */
    FIRE_ALARM_CANCEL(12),
    /**
     * <pre>
     * 歌曲演唱完成
     * </pre>
     *
     * <code>SONG_END = 13;</code>
     */
    SONG_END(13),
    /**
     * <pre>
     * 店家开始营业
     * </pre>
     *
     * <code>STARTING_BUSINESS = 14;</code>
     */
    STARTING_BUSINESS(14),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 其它
     * </pre>
     *
     * <code>ELSE = 0;</code>
     */
    public static final int ELSE_VALUE = 0;
    /**
     * <pre>
     * 开房
     * </pre>
     *
     * <code>ROOM_OPEN = 1;</code>
     */
    public static final int ROOM_OPEN_VALUE = 1;
    /**
     * <pre>
     * 关房
     * </pre>
     *
     * <code>ROOM_CLOSE = 2;</code>
     */
    public static final int ROOM_CLOSE_VALUE = 2;
    /**
     * <pre>
     * 机顶盒上线
     * </pre>
     *
     * <code>BOX_ONLINE = 3;</code>
     */
    public static final int BOX_ONLINE_VALUE = 3;
    /**
     * <pre>
     * 机顶盒下线
     * </pre>
     *
     * <code>BOX_OFFLINE = 4;</code>
     */
    public static final int BOX_OFFLINE_VALUE = 4;
    /**
     * <pre>
     * 服务器上线
     * </pre>
     *
     * <code>NODE_ONLINE = 5;</code>
     */
    public static final int NODE_ONLINE_VALUE = 5;
    /**
     * <pre>
     * 服务器下线
     * </pre>
     *
     * <code>NODE_OFFLINE = 6;</code>
     */
    public static final int NODE_OFFLINE_VALUE = 6;
    /**
     * <pre>
     * 火警预警
     * </pre>
     *
     * <code>EARLY_FIRE_ALARM = 7;</code>
     */
    public static final int EARLY_FIRE_ALARM_VALUE = 7;
    /**
     * <pre>
     * 火警 （此时需要将火警信号发给房间客人）
     * </pre>
     *
     * <code>FIRE_ALARM = 8;</code>
     */
    public static final int FIRE_ALARM_VALUE = 8;
    /**
     * <pre>
     * 疑似吸毒
     * </pre>
     *
     * <code>DRUG = 9;</code>
     */
    public static final int DRUG_VALUE = 9;
    /**
     * <pre>
     * 疑似未成年人
     * </pre>
     *
     * <code>MINORS = 10;</code>
     */
    public static final int MINORS_VALUE = 10;
    /**
     * <pre>
     * 点歌
     * </pre>
     *
     * <code>SONG = 11;</code>
     */
    public static final int SONG_VALUE = 11;
    /**
     * <pre>
     * 火警取消
     * </pre>
     *
     * <code>FIRE_ALARM_CANCEL = 12;</code>
     */
    public static final int FIRE_ALARM_CANCEL_VALUE = 12;
    /**
     * <pre>
     * 歌曲演唱完成
     * </pre>
     *
     * <code>SONG_END = 13;</code>
     */
    public static final int SONG_END_VALUE = 13;
    /**
     * <pre>
     * 店家开始营业
     * </pre>
     *
     * <code>STARTING_BUSINESS = 14;</code>
     */
    public static final int STARTING_BUSINESS_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SubType valueOf(int value) {
      return forNumber(value);
    }

    public static SubType forNumber(int value) {
      switch (value) {
        case 0: return ELSE;
        case 1: return ROOM_OPEN;
        case 2: return ROOM_CLOSE;
        case 3: return BOX_ONLINE;
        case 4: return BOX_OFFLINE;
        case 5: return NODE_ONLINE;
        case 6: return NODE_OFFLINE;
        case 7: return EARLY_FIRE_ALARM;
        case 8: return FIRE_ALARM;
        case 9: return DRUG;
        case 10: return MINORS;
        case 11: return SONG;
        case 12: return FIRE_ALARM_CANCEL;
        case 13: return SONG_END;
        case 14: return STARTING_BUSINESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SubType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SubType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SubType>() {
            public SubType findValueByNumber(int number) {
              return SubType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return StreamMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final SubType[] VALUES = values();

    public static SubType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SubType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StreamMessage.SubType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <pre>
   * 消息类型 0其它 1营业 2火警 3异常行为 4点歌
   * </pre>
   *
   * <code>int32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int SUB_TYPE_FIELD_NUMBER = 2;
  private int subType_;
  /**
   * <pre>
   * 子消息类型
   * </pre>
   *
   * <code>int32 sub_type = 2;</code>
   */
  public int getSubType() {
    return subType_;
  }

  public static final int DATE_FIELD_NUMBER = 3;
  private volatile Object date_;
  /**
   * <pre>
   * 消息发生时间
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  public String getDate() {
    Object ref = date_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息发生时间
   * </pre>
   *
   * <code>string date = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDateBytes() {
    Object ref = date_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KTV_NET_CODE_FIELD_NUMBER = 4;
  private volatile Object ktvNetCode_;
  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 4;</code>
   */
  public String getKtvNetCode() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvNetCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * KTV编号
   * </pre>
   *
   * <code>string ktv_net_code = 4;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNetCodeBytes() {
    Object ref = ktvNetCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvNetCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_CODE_FIELD_NUMBER = 5;
  private volatile Object roomCode_;
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 5;</code>
   */
  public String getRoomCode() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      roomCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>string room_code = 5;</code>
   */
  public com.google.protobuf.ByteString
      getRoomCodeBytes() {
    Object ref = roomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      roomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KTV_ROOM_CODE_FIELD_NUMBER = 9;
  private volatile Object ktvRoomCode_;
  /**
   * <pre>
   * KTV房间名
   * </pre>
   *
   * <code>string ktv_room_code = 9;</code>
   */
  public String getKtvRoomCode() {
    Object ref = ktvRoomCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvRoomCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * KTV房间名
   * </pre>
   *
   * <code>string ktv_room_code = 9;</code>
   */
  public com.google.protobuf.ByteString
      getKtvRoomCodeBytes() {
    Object ref = ktvRoomCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvRoomCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 6;
  private volatile Object content_;
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 6;</code>
   */
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 6;</code>
   */
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRA_FIELD_NUMBER = 7;
  private volatile Object extra_;
  /**
   * <pre>
   * 扩展内容（备用）
   * </pre>
   *
   * <code>string extra = 7;</code>
   */
  public String getExtra() {
    Object ref = extra_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展内容（备用）
   * </pre>
   *
   * <code>string extra = 7;</code>
   */
  public com.google.protobuf.ByteString
      getExtraBytes() {
    Object ref = extra_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KTV_NAME_FIELD_NUMBER = 8;
  private volatile Object ktvName_;
  /**
   * <pre>
   * KTV名称
   * </pre>
   *
   * <code>string ktv_name = 8;</code>
   */
  public String getKtvName() {
    Object ref = ktvName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ktvName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * KTV名称
   * </pre>
   *
   * <code>string ktv_name = 8;</code>
   */
  public com.google.protobuf.ByteString
      getKtvNameBytes() {
    Object ref = ktvName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ktvName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != 0) {
      output.writeInt32(1, type_);
    }
    if (subType_ != 0) {
      output.writeInt32(2, subType_);
    }
    if (!getDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, date_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roomCode_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, content_);
    }
    if (!getExtraBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extra_);
    }
    if (!getKtvNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ktvName_);
    }
    if (!getKtvRoomCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ktvRoomCode_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (subType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, subType_);
    }
    if (!getDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, date_);
    }
    if (!getKtvNetCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ktvNetCode_);
    }
    if (!getRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, roomCode_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, content_);
    }
    if (!getExtraBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extra_);
    }
    if (!getKtvNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ktvName_);
    }
    if (!getKtvRoomCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ktvRoomCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StreamMessage)) {
      return super.equals(obj);
    }
    StreamMessage other = (StreamMessage) obj;

    if (getType()
        != other.getType()) return false;
    if (getSubType()
        != other.getSubType()) return false;
    if (!getDate()
        .equals(other.getDate())) return false;
    if (!getKtvNetCode()
        .equals(other.getKtvNetCode())) return false;
    if (!getRoomCode()
        .equals(other.getRoomCode())) return false;
    if (!getKtvRoomCode()
        .equals(other.getKtvRoomCode())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getExtra()
        .equals(other.getExtra())) return false;
    if (!getKtvName()
        .equals(other.getKtvName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + SUB_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSubType();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + KTV_NET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvNetCode().hashCode();
    hash = (37 * hash) + ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRoomCode().hashCode();
    hash = (37 * hash) + KTV_ROOM_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getKtvRoomCode().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + KTV_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getKtvName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StreamMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StreamMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StreamMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StreamMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StreamMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 流水消息
   * </pre>
   *
   * Protobuf type {@code StreamMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamMessage)
      com.bestarmedia.proto.monitor.StreamMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MonitorProto.internal_static_StreamMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MonitorProto.internal_static_StreamMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StreamMessage.class, Builder.class);
    }

    // Construct using com.bestarmedia.proto.monitor.StreamMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      subType_ = 0;

      date_ = "";

      ktvNetCode_ = "";

      roomCode_ = "";

      ktvRoomCode_ = "";

      content_ = "";

      extra_ = "";

      ktvName_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MonitorProto.internal_static_StreamMessage_descriptor;
    }

    @Override
    public StreamMessage getDefaultInstanceForType() {
      return StreamMessage.getDefaultInstance();
    }

    @Override
    public StreamMessage build() {
      StreamMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StreamMessage buildPartial() {
      StreamMessage result = new StreamMessage(this);
      result.type_ = type_;
      result.subType_ = subType_;
      result.date_ = date_;
      result.ktvNetCode_ = ktvNetCode_;
      result.roomCode_ = roomCode_;
      result.ktvRoomCode_ = ktvRoomCode_;
      result.content_ = content_;
      result.extra_ = extra_;
      result.ktvName_ = ktvName_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StreamMessage) {
        return mergeFrom((StreamMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StreamMessage other) {
      if (other == StreamMessage.getDefaultInstance()) return this;
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getSubType() != 0) {
        setSubType(other.getSubType());
      }
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      if (!other.getKtvNetCode().isEmpty()) {
        ktvNetCode_ = other.ktvNetCode_;
        onChanged();
      }
      if (!other.getRoomCode().isEmpty()) {
        roomCode_ = other.roomCode_;
        onChanged();
      }
      if (!other.getKtvRoomCode().isEmpty()) {
        ktvRoomCode_ = other.ktvRoomCode_;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        onChanged();
      }
      if (!other.getKtvName().isEmpty()) {
        ktvName_ = other.ktvName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StreamMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StreamMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     * 消息类型 0其它 1营业 2火警 3异常行为 4点歌
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型 0其它 1营业 2火警 3异常行为 4点歌
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型 0其它 1营业 2火警 3异常行为 4点歌
     * </pre>
     *
     * <code>int32 type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int subType_ ;
    /**
     * <pre>
     * 子消息类型
     * </pre>
     *
     * <code>int32 sub_type = 2;</code>
     */
    public int getSubType() {
      return subType_;
    }
    /**
     * <pre>
     * 子消息类型
     * </pre>
     *
     * <code>int32 sub_type = 2;</code>
     */
    public Builder setSubType(int value) {
      
      subType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 子消息类型
     * </pre>
     *
     * <code>int32 sub_type = 2;</code>
     */
    public Builder clearSubType() {
      
      subType_ = 0;
      onChanged();
      return this;
    }

    private Object date_ = "";
    /**
     * <pre>
     * 消息发生时间
     * </pre>
     *
     * <code>string date = 3;</code>
     */
    public String getDate() {
      Object ref = date_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息发生时间
     * </pre>
     *
     * <code>string date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息发生时间
     * </pre>
     *
     * <code>string date = 3;</code>
     */
    public Builder setDate(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息发生时间
     * </pre>
     *
     * <code>string date = 3;</code>
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息发生时间
     * </pre>
     *
     * <code>string date = 3;</code>
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }

    private Object ktvNetCode_ = "";
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 4;</code>
     */
    public String getKtvNetCode() {
      Object ref = ktvNetCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvNetCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNetCodeBytes() {
      Object ref = ktvNetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvNetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 4;</code>
     */
    public Builder setKtvNetCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvNetCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 4;</code>
     */
    public Builder clearKtvNetCode() {
      
      ktvNetCode_ = getDefaultInstance().getKtvNetCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV编号
     * </pre>
     *
     * <code>string ktv_net_code = 4;</code>
     */
    public Builder setKtvNetCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvNetCode_ = value;
      onChanged();
      return this;
    }

    private Object roomCode_ = "";
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 5;</code>
     */
    public String getRoomCode() {
      Object ref = roomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        roomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRoomCodeBytes() {
      Object ref = roomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        roomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 5;</code>
     */
    public Builder setRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 5;</code>
     */
    public Builder clearRoomCode() {
      
      roomCode_ = getDefaultInstance().getRoomCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间号
     * </pre>
     *
     * <code>string room_code = 5;</code>
     */
    public Builder setRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomCode_ = value;
      onChanged();
      return this;
    }

    private Object ktvRoomCode_ = "";
    /**
     * <pre>
     * KTV房间名
     * </pre>
     *
     * <code>string ktv_room_code = 9;</code>
     */
    public String getKtvRoomCode() {
      Object ref = ktvRoomCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvRoomCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * KTV房间名
     * </pre>
     *
     * <code>string ktv_room_code = 9;</code>
     */
    public com.google.protobuf.ByteString
        getKtvRoomCodeBytes() {
      Object ref = ktvRoomCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvRoomCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * KTV房间名
     * </pre>
     *
     * <code>string ktv_room_code = 9;</code>
     */
    public Builder setKtvRoomCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvRoomCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV房间名
     * </pre>
     *
     * <code>string ktv_room_code = 9;</code>
     */
    public Builder clearKtvRoomCode() {
      
      ktvRoomCode_ = getDefaultInstance().getKtvRoomCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV房间名
     * </pre>
     *
     * <code>string ktv_room_code = 9;</code>
     */
    public Builder setKtvRoomCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvRoomCode_ = value;
      onChanged();
      return this;
    }

    private Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     */
    public Builder setContent(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 6;</code>
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      content_ = value;
      onChanged();
      return this;
    }

    private Object extra_ = "";
    /**
     * <pre>
     * 扩展内容（备用）
     * </pre>
     *
     * <code>string extra = 7;</code>
     */
    public String getExtra() {
      Object ref = extra_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 扩展内容（备用）
     * </pre>
     *
     * <code>string extra = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展内容（备用）
     * </pre>
     *
     * <code>string extra = 7;</code>
     */
    public Builder setExtra(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extra_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展内容（备用）
     * </pre>
     *
     * <code>string extra = 7;</code>
     */
    public Builder clearExtra() {
      
      extra_ = getDefaultInstance().getExtra();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展内容（备用）
     * </pre>
     *
     * <code>string extra = 7;</code>
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extra_ = value;
      onChanged();
      return this;
    }

    private Object ktvName_ = "";
    /**
     * <pre>
     * KTV名称
     * </pre>
     *
     * <code>string ktv_name = 8;</code>
     */
    public String getKtvName() {
      Object ref = ktvName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ktvName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * KTV名称
     * </pre>
     *
     * <code>string ktv_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getKtvNameBytes() {
      Object ref = ktvName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ktvName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * KTV名称
     * </pre>
     *
     * <code>string ktv_name = 8;</code>
     */
    public Builder setKtvName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ktvName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV名称
     * </pre>
     *
     * <code>string ktv_name = 8;</code>
     */
    public Builder clearKtvName() {
      
      ktvName_ = getDefaultInstance().getKtvName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * KTV名称
     * </pre>
     *
     * <code>string ktv_name = 8;</code>
     */
    public Builder setKtvNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ktvName_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamMessage)
  }

  // @@protoc_insertion_point(class_scope:StreamMessage)
  private static final StreamMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StreamMessage();
  }

  public static StreamMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamMessage>
      PARSER = new com.google.protobuf.AbstractParser<StreamMessage>() {
    @Override
    public StreamMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public StreamMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

